<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
    <UseWindowsForms>True</UseWindowsForms>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../ScriptTrainer.UI/ScriptTrainer.UI.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
